import type {Metadata} from "next";
import {Montserrat} from "next/font/google";
import "./globals.css";
import React from "react";
import {NavLinks} from "@/app/ui/navLinks/nav-links";

const inter = Montserrat({
    weight: ["400", "500", "600", "700", "800", "900"],
    subsets: ["latin"],
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    openGraph: {}
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <body className={inter.className}>
            <nav>
                <NavLinks/>
            </nav>
            <main>
                {children}
            </main>
            <footer>
                Footer
            </footer>
            </body>
        </html>
    );
}
